version: "3"

services:
    hugo:
        build:
            context: ..
            dockerfile: docker/Dockerfile-hugo
        volumes:
            - ..:/src:rw
            - public:/tmp/html:rw
        environment:
            - HUGO_BASE_URL=${PUBLIC_SCHEME}://${VIRTUAL_HOST}

    nginx:
        build:
            context: ..
            dockerfile: docker/Dockerfile-nginx
        volumes:
            - public:/usr/share/nginx/html:ro
        expose:
            - 80
        environment:
            - VIRTUAL_HOST=${VIRTUAL_HOST}
            - VIRTUAL_PORT=80
            - VIRTUAL_NETWORK=nginx-proxy
        networks:
            - nginx-proxy

volumes:
    public:

networks:
    nginx-proxy:
        external: true

